-- =============================================================================
-- V1__create_projects_table.sql
-- Flyway migration: initial schema for the Project Management Service.
-- =============================================================================

-- Enable the pgcrypto extension so we can use gen_random_uuid() if needed,
-- though the application generates UUIDs in Java.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- projects table
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id          UUID         NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
    owner_id    UUID         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT chk_projects_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETED'))
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

-- Frequently queried by owner
CREATE INDEX IF NOT EXISTS idx_projects_owner_id
    ON projects (owner_id);

-- Frequently filtered by status
CREATE INDEX IF NOT EXISTS idx_projects_status
    ON projects (status);

-- Composite index for owner + status queries
CREATE INDEX IF NOT EXISTS idx_projects_owner_status
    ON projects (owner_id, status);

-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------
COMMENT ON TABLE  projects             IS 'Stores all project records managed by the Project Management Service.';
COMMENT ON COLUMN projects.id          IS 'Universally unique identifier for the project, generated by the application layer.';
COMMENT ON COLUMN projects.name        IS 'Human-readable project name; must not be blank.';
COMMENT ON COLUMN projects.description IS 'Optional free-text description of the project.';
COMMENT ON COLUMN projects.status      IS 'Lifecycle status: ACTIVE, ARCHIVED, or DELETED (soft-delete).';
COMMENT ON COLUMN projects.owner_id    IS 'UUID of the user who owns this project (foreign key managed externally).';
COMMENT ON COLUMN projects.created_at  IS 'Timestamp (UTC) when the project was first persisted.';
COMMENT ON COLUMN projects.updated_at  IS 'Timestamp (UTC) of the most recent update to this record.';
